name: purity_memory_profile_test
version: 0.0.0
author: Daniel Robinson <daniel.robinson.dart@gmail.com>
description: simple purity app to profile memory usage.
dependencies:
  controls_and_panels: '>=0.1.0 <0.2.0'
  purity: '>=0.4.2 <0.5.0'
