name: purity_memory_profile_test
version: 0.0.0
author: Daniel Robinson <daniel.robinson.dart@gmail.com>
description: simple purity app to profile memory usage.
dependencies:
  controls_and_panels: '>=0.8.6 <0.9.0'
  purity: '>=0.8.5 <0.9.0'
